### ISSUE TITLE
Inputs randomy rotate on game restart

### ISSUE THREAD

**Issue by kipteamm** [kipteamm/BitBattles#9]
Some inputs, not all, could be rotated (but not visually) after a battle was restarted. To clarify: visually the inputs are looking the way they are supposed to, but when you try to click the connector, you'll find it is on one of the other sides of the gate, and not the one with the visual indicator.

**Comment by WeiseSchokolade** [comment]
Could be fixed in #12

**Comment by kipteamm** [comment]
Yes I believe you are right.
